### PR TITLE
Added optional startupQuerySelector

### PR DESCRIPTION
**Pull request by ridersshare**
added optional meteor package setting "startupQuerySelector" to enable custom selection of which users will have their status fields reset... FYI i was checking out the github.dev editor and it did some formatting on `18` and `187-191`

### CODE REVIEW

**Review by filipenevola — APPROVED** [review]
Sounds good.

**Comment by filipenevola** [comment]
@StorytellerCZ, could you double-check and merge/publish if you agree? Thanks!

**Review by StorytellerCZ — APPROVED** [review]

**Comment by StorytellerCZ** [comment]
Looks fine, but it would be nice to document this feature.

**Comment by ridersshare** [comment]
> Looks fine, but it would be nice to document this feature.

You got it :D - https://github.com/Meteor-Community-Packages/meteor-user-status/pull/180

**Pull request merged**
