### PR TITLE
v1.1.0 release

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
We will need to re-work the CI completely here, but I would keep that for v2.

**Comment by StorytellerCZ** [comment]
We could add #163 to this release as well, though it might be better for v2 as it changes how things behaved until now.

**Comment by jankapunkt** [comment]
So new ci is not going into this release?

**Review by filipenevola — CHANGES_REQUESTED** [review]
I think [this](https://github.com/Meteor-Community-Packages/meteor-user-status/pull/178) change is missing, right? I don't think the content of this PR is here

**Review by filipenevola — APPROVED** [review]
LGTM

**Pull request merged**
