### PR TITLE
Update mizzao:timesync

### PR DESCRIPTION
**Pull request by Brouilles**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
The tests are failing pretty bad. Looks like there were some breaking changes. @Brouilles Do you want to look into it?

**Comment by mizzao** [comment]
Seems like one of the reasons is because `Meteor.flush()` got removed in some recent version...

**Comment by StorytellerCZ** [comment]
Back in v0.5.8 `Meteor.flush()` got deprecated and renamed to `Deps.flush()`. I think this is now tracker: https://docs.meteor.com/api/tracker.html#Tracker-flush

**Comment by StorytellerCZ** [comment]
Looking to fix this in: https://github.com/Meteor-Community-Packages/meteor-user-status/pull/123

**Pull request merged**
