### PR TITLE
Instructions for contribution

### PR DESCRIPTION
**Pull request by mizzao**
Hey guys, I just wanted to write down some instructions for contributing and publishing before they got lost to the aether. It might help organize and remember things in the future.

I'm not actively using this package, so feel free to do with this what you wish. You might want to expand the TravisCI section, and let me know if I can help with figuring out how to publish to https://user-status.meteorapp.com.

### CODE REVIEW

**Comment by mizzao** [comment]
@wreiske I wanted to write down some stuff about maintaining so that next time you, I, or others wanted to update this package we would know what to do. Did you want to add anything about the badges or other things people should know?

I even forget myself what I used to after a couple of years of not looking at this, so I figure it doesn't hurt to write it down.

**Comment by wreiske** [comment]
Sure. I'll add some info about the badges and checking LGTM, lint, etc., once I get some free time. 👍

**Comment by StorytellerCZ** [comment]
Good start. We should probably add as much stuff from https://github.com/Meteor-Community-Packages/template-package as possible.

**Comment by StorytellerCZ** [comment]
@mizzao Do you want to continue or merge this as is?

**Comment by mizzao** [comment]
I think I added everything I wanted, you can add what you wish and merge.

**Pull request merged**
